eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  instance:
    hostname: localhost

orderURL:
  http://PAYMENT-SERVICE/payment/doPayment
paymentURL:
  http://ORDER-SERVICE/order/bookOrder
